### ISSUE TITLE
Small issue when the first record is the one you need.

### ISSUE THREAD

**Issue by gitjos** [hanpq/getps.dev#1]
Current example:
   while ($Index -ne -1) {
      $Index = system.array]::IndexOf($DatabaseIndex,$SearchString,$Index+1)
      if ($Index -ne -1) {
         $Array += $Index
      }
   } 
By doing the next record you miss the first record. This can be solved this way:
Improved
  while ($Index -ne -1) {
      $Index = [array]::IndexOf($DatabaseIndex,$SearchString,$Index)
      if ($Index -ne -1) {
         $Array += $Index
         $Index++
      }
Thank you for sharing this example helped me forward.

      
   }

**Comment by hanpq** [comment]
Yes completly true, I'll correct that, Thanks!
